name: Deploy to Google

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@main
       - name: Install dependencies
         run: npm ci
       - name: Build dependencies
         run: npm run build
       - name: Archive production artifact
         uses: actions/upload-artifact@main
         with:
            name: dist
            path: dist
       - name: install firebase
         run: npm i firebase-tools -g  
       - name: deploy
         run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
